name: domain
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.6.0
publish_to: "none"
# Add regular dependencies here.
dependencies:
  common:
    path: ../common
  data:
    path: ../data
  path: ^1.8.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.6
  dartz: ^0.10.1
  get_it: ^8.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
