name: di
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
publish_to: "none"
# Add regular dependencies here.
dependencies:
  common:
    path: ../common
  data:
    path: ../data
  domain:
    path: ../domain
  path: ^1.8.0
  retrofit: ^4.7.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  dio: ^5.8.0+1
  get_it: ^8.2.0
  # data: ^0.15.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  http: ^1.4.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
